language: c
sudo: false
addons:
  apt:
    packages:
      - ksh
      - libgd2-xpm-dev
      - tcl-dev
      - libdevil-dev
      - libxaw7-dev
      - freeglut3-dev

script:
  - ./autogen.sh
  - ./configure
  - make
  - make install
  - make check
