language: c
dist: trusty
sudo: required

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - clang
    - ksh
    - libgd2-xpm-dev
    - tcl-dev
    - libdevil-dev
    - libxaw7-dev
    - freeglut3-dev
    - libgd-dev

services:
- docker

env:
- BUILD_SYSTEM=autotools

- BUILD_SYSTEM=cmake

- BUILD_SYSTEM=autotools
  DOCKER_BUILD=TRUE

- BUILD_SYSTEM=cmake
  DOCKER_BUILD=TRUE

matrix:
  include:
  - env: BUILD_SYSTEM=autotools SONARQUBE=TRUE
    compiler: gcc
    addons:
      sonarqube:
        organization: "erwinjanssen-github"
        token:
          secure: "u4H26XoghRdg9ZKPZE/C+zgSkcHkYI+4Q5wR1QaNJUknUDODfKe2iMH7G9HqW/ON8yVNqFnirc8XA2JRqvag3yEGITLpM0uycL+j6UTeXyQ8mw91hz7bXRv05DoU4GtzTn0145685alTeYtgbJ8B+CooxdqAfj1NJnrISIcnB/ZXvvb8l97UjZwNsCBomptLH/n69cESIQLTfz9PiIXapWhcpEJh0U0Sbq7/ToP22d0/Nu0i9yrLeAhsxJu/9zha4DfbqgO2lXwWvZ88ja8RABMD32gJE5l4CDWfLk+wFEbqLXLx84mkxQPwvZ8fXVsBSLySYKjq3QceQGZCzD0icC4JjYLBsNjwQIgVLB5blu5o8QCvaUYubOFySfNwwHQCCXnwyLmw8lq5PaALfA/rp4md3DgnjFxSgTV2DwbsjqkbEWnSAqPD2cZB4I5oXYTwuHbsT55YbIiQgSvjfuGLFXHxVeOChqpadR5cafQiGAqytTFTBcvMmn86Q4RZ9ZCvglMrL02DJg5zsCRajPIrXZDY7PBL+FV4uYeGKdNaMt6jJgd/sDoAQh5/nFCDE8SLvjA2Yg8wxNKKWPJuJaRMjfr5seDt+x/05OrvptnPEwGmXsEMQZwyFQ4j5yMhbqPFYtUa9QApHFGeEVC3hyUBw/xE55sudBfAOMLa9cVVhIM="
        branches:
          - analyze


install:
# Install unit testing framework Criterion.
- cd dependencies/criterion
- mkdir build
- cd build
- cmake ..
- cmake --build .
- sudo make install
- sudo ldconfig
- cd ${TRAVIS_BUILD_DIR}
- if [ ${DOCKER_BUILD} ] ; then docker build -t centos7-build-env ci/centos7/ ; fi

script:
- sudo ./ci/travis-script.sh

before_deploy:
- export DEPLOYED_FILE=$(ls *.tar.gz)
- echo "deploying ${DEPLOYED_FILE} to GitHub releases"
- sudo chown travis ${DEPLOYED_FILE}

# If no tag is set, deploy as nightly
- if [ !${TRAVIS_TAG} ] ; then export TRAVIS_TAG=Nightly ; fi

deploy:
  provider: releases
  api_key:
    secure: EmdyQU0yNlq2mYtCz4xRj1Eyd73s5xYcD5tP+E42QmQhCoTSD0nb7J6H9MlzAXby2lgqDxcINvkXuEWGyySi4QHs32H7THbKs0U/dD7FuC7zFIfd2o/Q0kWyASTm8hPwu/OghmitmBXy37+QdfO4Snzy+AqVmHH3VtUax3kf0+qg12fQiNsDRXFJfO9mBddKNjxktjmfdN87pNfcVcNkCZz5DDs91ldIr6FiC+YMbfedtXqEjkavYSpFU/IX6/GJ9suJseGNH7+hmlSfw9yZT5TNd/8dnmUr2j4cD6pKgZWBQfWE/GmoJbYFbfIYfFzkwvLm3OEbr0rnsNabvKmApGpr8XBiO+w1raEXHXLsblp7eQi2BdQFu2QmVhh6vQP0uqAM12oEoC+m2FtR5WVy43RHA4tvK4hddikfUcRDRFQov9rqXj6x/cdmEhuimjugTbzmekrZ9RITucOs6YLtLry05oUjED1AD47rknTJAmZ3W93LANY7CLt8JsLhAODCZO/lTRhrXGOE2mSEiq/fqw2ZPrDPjI8J2BysYO7xb+IW1/S3seOnzL0m2Ox0wZkvDZyg9+HfjIa8AcCdJZ7EXlfDL+ExXcSbGTzwWhvy48f249cSjKM96q0SmVcIyCEapgFSIOyLSYQv3i/+5PB/ZLVT2rOdvj6zPVymAhAxEX4=
  skip_cleanup: true
  file: "${DEPLOYED_FILE}"
  on:
    repo: ellson/graphviz
    condition: ${DOCKER_BUILD} && ${BUILD_SYSTEM} == "autotools"

notifications:
  email:
    on_success: always

cache:
  directories:
  - '$HOME/.sonar/cache'
