language: c
sudo: true
addons:
  apt:
    packages:
    - ksh
    - libgd2-xpm-dev
    - tcl-dev
    - libdevil-dev
    - libxaw7-dev
    - freeglut3-dev
    - colorgcc

services:
- docker

env:
  global:
    # Coverity key
    - secure: "K2rMy5N38otq5Tg64fxTaPxS+lmrCNrvRaLQXbLbb8fWX2X+bErX9QsR6W96+L9p/0H512U/sagPUqwR9FwIG/VanFWdidjJTOffDmDwLAKAG9MDZKXm6tZNuvKtIXkxMRGnn1jmvtP3IyNaUI/yaLsyt5Fbzf7Fd8mSHi2JAjeeu9bftRC9ejk9dXGDoKPa8C3kZTO/xmpWWoZLxeJt4911bdH2GCHDDE6I2U82YQfoRbaqeqHVAlPl5/+98hVtfbmegfrOETeRGw0Va4MiCxvzw/Dqbdb5URtEaX9y881RplqJf2tjDNrhBbmm0Nx1YrtLGjzcS0QdYAe3QcDfi1SUeCP0XWur1yuOum93DiC0tM3djiDVojhaotEMIs1tumE/pOXMKsM+Zv+Fexc+/zUT9luTtRS/NILUcnIOnremo0C1InzRQfXSBoRgdyNr+htntKKuZGT1t32FGkUZo5bQ8dgED5z6OzGchWOJNEwONk4sK4xnkwsL9Cxov/oc2zkIrVfwqEfsqy6oB4/EY+45B5XvbxT2ogpk9+Vshov8N6ZNIQOMe5YYSlmx/b/FVo/LELSSNxal5bk3YtvVa2EqrN/opipDjqPmDrMKFnecYZHyEdEfFS8Hfsdsvuewym0WI3smMsz8W8Cuy099PV+L58xuXy59lew7xaaRhuA="
  
  matrix:
    - DOCKER_BUILD=FALSE
    - DOCKER_BUILD=TRUE

before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ErwinJanssen/graphviz"
      description: "Build submitted via Travis CI"
    notification_email: erwinjanssen@outlook.com
    build_command_prepend: "./autogen.sh; make clean"
    build_command: "make"
    branch_pattern: coverity-scan

install:
# Install unit testing framework Criterion.
- cd dependencies/criterion
- mkdir build
- cd build
- cmake ..
- cmake --build .
- sudo make install
- sudo ldconfig
- cd ${TRAVIS_BUILD_DIR}
- if [ ${DOCKER_BUILD} == "TRUE" ] ; then docker build -t centos7-build-env ci/centos7/ ; fi
    
script:
- cd ${TRAVIS_BUILD_DIR}
- if [ ${DOCKER_BUILD} == "FALSE" ] ; then sudo ./ci/build_and_test.sh ; fi
- if [ ${DOCKER_BUILD} == "TRUE" ] ; then docker run --rm -v `pwd`:/graphviz -w /graphviz -i -t centos7-build-env bash "ci/build_and_test.sh" ; fi

before_deploy:
- export DEPLOYED_FILE=$(ls *.tar.gz)
- echo "deploying ${DEPLOYED_FILE} to GitHub releases"
- sudo chown travis ${DEPLOYED_FILE}

# If no tag is set, deploy as nightly
- if [ !${TRAVIS_TAG} ] ; then export TRAVIS_TAG=Nightly ; fi

deploy:
  provider: releases
  api_key:
    secure: EmdyQU0yNlq2mYtCz4xRj1Eyd73s5xYcD5tP+E42QmQhCoTSD0nb7J6H9MlzAXby2lgqDxcINvkXuEWGyySi4QHs32H7THbKs0U/dD7FuC7zFIfd2o/Q0kWyASTm8hPwu/OghmitmBXy37+QdfO4Snzy+AqVmHH3VtUax3kf0+qg12fQiNsDRXFJfO9mBddKNjxktjmfdN87pNfcVcNkCZz5DDs91ldIr6FiC+YMbfedtXqEjkavYSpFU/IX6/GJ9suJseGNH7+hmlSfw9yZT5TNd/8dnmUr2j4cD6pKgZWBQfWE/GmoJbYFbfIYfFzkwvLm3OEbr0rnsNabvKmApGpr8XBiO+w1raEXHXLsblp7eQi2BdQFu2QmVhh6vQP0uqAM12oEoC+m2FtR5WVy43RHA4tvK4hddikfUcRDRFQov9rqXj6x/cdmEhuimjugTbzmekrZ9RITucOs6YLtLry05oUjED1AD47rknTJAmZ3W93LANY7CLt8JsLhAODCZO/lTRhrXGOE2mSEiq/fqw2ZPrDPjI8J2BysYO7xb+IW1/S3seOnzL0m2Ox0wZkvDZyg9+HfjIa8AcCdJZ7EXlfDL+ExXcSbGTzwWhvy48f249cSjKM96q0SmVcIyCEapgFSIOyLSYQv3i/+5PB/ZLVT2rOdvj6zPVymAhAxEX4=
  skip_cleanup: true
  file: "${DEPLOYED_FILE}"
  on:
    repo: ellson/graphviz
    condition: ${DOCKER_BUILD} == "FALSE"

notifications:
  email:
    recipients:
      - john.ellson@comcast.net
    on_success: always
